#import "config.typ": initialize
#show: initialize

#include "content/index.typ"
#include "content/404.typ"

#include "content/posts/20180215-use-lxrunoffline-to-install-arch-linux/index.typ"
#include "content/posts/20180405-type-safe-printf-in-idris.typ"
#include "content/posts/20180725-run-vscode-on-archlinux-on-wsl/index.typ"
#include "content/posts/20190908-higher-kinded-types-in-typescript.typ"
#include "content/posts/20200620-library-at-the-end-of-space-and-time.typ"
#include "content/posts/20200723-frost-flower.typ"
#include "content/posts/20200815-twelve-light-minutes.typ"
#include "content/posts/20210407-edge-case.typ"
#include "content/posts/20210410-beast-and-human.typ"
#include "content/posts/20210716-full-notes-of-installing-arch-in-2021.typ"
#include "content/posts/20211030-a-letter-to-a-stranger.typ"
#include "content/posts/20211101-suiciding-ghost.typ"
#include "content/posts/20211225-twenty-twenty-one.typ"
#include "content/posts/20220316-singularity.typ"
#include "content/posts/20220405-gravestone.typ"
#include "content/posts/20220507-sunken-in-wind.typ"
#include "content/posts/20220728-introducing-google-fonts-plus.typ"
#include "content/posts/20221005-donglingshan/index.typ"
#include "content/posts/20230102-twenty-twenty-two.typ"

#include "content/collections/conlang-tutorial/index.typ"
#include "content/collections/conlang-tutorial/0-introduction.typ"
#include "content/collections/conlang-tutorial/1-phonology/index.typ"
#include "content/collections/conlang-tutorial/1-phonology/1-pronounciation/index.typ"

#include "content/collections/eighteen/index.typ"
#include "content/collections/eighteen/20201101-mountain-climbing.typ"
#include "content/collections/eighteen/20201112-after-supper.typ"
#include "content/collections/eighteen/20210216-snowy-night.typ"
#include "content/collections/eighteen/20210320-missing-dream.typ"
#include "content/collections/eighteen/20210525-fantasyland.typ"
#include "content/collections/eighteen/20210610-gaokao-journal.typ"
#include "content/collections/eighteen/20210613-short-poems.typ"
#include "content/collections/eighteen/20210616-afterword.typ"

#include "content/collections/gifts/index.typ"
#include "content/collections/gifts/20220414-husky-in-the-lab.typ"

#include "content/collections/rubble/index.typ"
#include "content/collections/rubble/20211110-river-sand.typ"
#include "content/collections/rubble/20220520-water-flow.typ"

#include "content/collections/trpg-character-backstories/index.typ"
#include "content/collections/trpg-character-backstories/20211010-extinguished.typ"
#include "content/collections/trpg-character-backstories/20220120-oracle.typ"
#include "content/collections/trpg-character-backstories/20221027-escaping-eagle.typ"
#include "content/collections/trpg-character-backstories/20221124-buzzing-of-horror.typ"
#include "content/collections/trpg-character-backstories/20230302-light-deprived-child.typ"
#include "content/collections/trpg-character-backstories/20230720-1-kuto-and-amandla.typ"
#include "content/collections/trpg-character-backstories/20230720-2-agony-onyx.typ"
